version: '3.9'

services:

#  zaman_discovery_service:
#    container_name: discovery_service_container
#    build: zaman_discovery_service/
#    image: zaman/discovery-service
#    restart: always
#    ports:
#      - '8761:8761'


  zaman_gateway_service:
    container_name: gateway_service_container
    build: zaman_gateway_service/
    image: zaman/gateway-service
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - zaman-application-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/zamanDB
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin


  mysql:
    container_name: zaman_mysql_instance
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'zamanDB'
      MYSQL_ROOT_PASSWORD: 'admin'
      MYSQL_ROOT_HOST: '%'
    ports:
        - '3306:3306'
    volumes:
      - zamanDB:/var/lib/mysql


  zaman-application-service:
    container_name: application_service_container
    build: zaman_application_service/
    image: zaman/application-service
    restart: always
    ports:
      - '8081:8081'
    depends_on:
      - mysql
      - rabbitmq
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/zamanDB
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_RABBITMQ_HOST=rabbitmq


  zaman-worker-service:
    container_name: worker_service_container
    build: zaman_worker_service/
    image: zaman/worker-service
    restart: always
    ports:
      - '8086:8086'
    depends_on:
      - mysql
      - rabbitmq
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/zamanDB
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_RABBITMQ_HOST=rabbitmq


  zaman_mail_service:
    container_name: mail_service_container
    build: zaman_mail_service/
    image: zaman/mail-service
    restart: always
    ports:
      - '8082:8082'
    depends_on:
      - rabbitmq
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/zamanDB
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_RABBITMQ_HOST=rabbitmq
      - JWT_SECRET=loremipsumfoobarjohndoe


  rabbitmq:
    container_name: zaman_rabbitmq_instance
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

  web:
    image: zaman/web-client
    build: zaman_web_client/
    container_name: zaman-web-client
    restart: always
    ports:
      - "8085:80"

# Where we store our data
volumes:
  zamanDB:


