name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: |
          sudo /etc/init.d/mysql start
          mysql -e 'ALTER USER "root"@"localhost" IDENTIFIED BY "admin"' -uroot -proot
          mysql -e 'CREATE DATABASE zamanDB;' -uroot -padmin
          mysql -e 'SHOW DATABASES;' -uroot -padmin
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
